# coding: utf-8

"""
    Visier Consolidated Analytics APIs

    Visier APIs for managing consolidated analytics (CA) tenants.

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

import unittest

import os
from pprint import pprint
from visier_consolidated_analytics_python_sdk import VisierConsolidatedAnalytics

class TestSimple(unittest.TestCase):
    def setUp(self):
        pass

    def test_client(self):
        visierconsolidatedanalytics = VisierConsolidatedAnalytics(
        )
        self.assertIsNotNone(visierconsolidatedanalytics)

    def tearDown(self):
        pass


if __name__ == "__main__":
    unittest.main()
