# coding: utf-8

"""
    Visier Consolidated Analytics APIs

    Visier APIs for managing consolidated analytics (CA) tenants.

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from visier_consolidated_analytics_python_sdk.paths.v1alpha_admin_consolidated_analytics_tenants_tenant_id_excluded_sources.patch import AddExcludedSources
from visier_consolidated_analytics_python_sdk.paths.v1alpha_admin_consolidated_analytics_tenants_tenant_id_source_tenants.patch import AddSourceTenants
from visier_consolidated_analytics_python_sdk.paths.v1alpha_admin_consolidated_analytics_tenants.post import CreateTenant
from visier_consolidated_analytics_python_sdk.paths.v1alpha_admin_consolidated_analytics_tenants_tenant_id_excluded_sources.get import ListExcludedSources
from visier_consolidated_analytics_python_sdk.paths.v1alpha_admin_consolidated_analytics_tenants_tenant_id_source_tenants.get import ListSourceTenants
from visier_consolidated_analytics_python_sdk.paths.v1alpha_admin_consolidated_analytics_tenants.get import ListTenants
from visier_consolidated_analytics_python_sdk.paths.v1alpha_admin_consolidated_analytics_tenants_tenant_id_excluded_sources.delete import RemoveExcludedSources
from visier_consolidated_analytics_python_sdk.paths.v1alpha_admin_consolidated_analytics_tenants_tenant_id_source_tenants.delete import RemoveSourceTenants
from visier_consolidated_analytics_python_sdk.paths.v1alpha_admin_consolidated_analytics_tenants_tenant_id_excluded_sources.put import SetExcludedSources
from visier_consolidated_analytics_python_sdk.paths.v1alpha_admin_consolidated_analytics_tenants_tenant_id_source_tenants.put import SetSourceTenants
from visier_consolidated_analytics_python_sdk.apis.tags.consolidated_analytics_v1_alpha_api_raw import ConsolidatedAnalyticsV1AlphaApiRaw


class ConsolidatedAnalyticsV1AlphaApi(
    AddExcludedSources,
    AddSourceTenants,
    CreateTenant,
    ListExcludedSources,
    ListSourceTenants,
    ListTenants,
    RemoveExcludedSources,
    RemoveSourceTenants,
    SetExcludedSources,
    SetSourceTenants,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: ConsolidatedAnalyticsV1AlphaApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = ConsolidatedAnalyticsV1AlphaApiRaw(api_client)
