# coding: utf-8

"""
    Visier Consolidated Analytics APIs

    Visier APIs for managing consolidated analytics (CA) tenants.

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from visier_consolidated_analytics_python_sdk.paths.v1alpha_admin_consolidated_analytics_tenants_tenant_id_excluded_sources.patch import AddExcludedSourcesRaw
from visier_consolidated_analytics_python_sdk.paths.v1alpha_admin_consolidated_analytics_tenants_tenant_id_source_tenants.patch import AddSourceTenantsRaw
from visier_consolidated_analytics_python_sdk.paths.v1alpha_admin_consolidated_analytics_tenants.post import CreateTenantRaw
from visier_consolidated_analytics_python_sdk.paths.v1alpha_admin_consolidated_analytics_tenants_tenant_id_excluded_sources.get import ListExcludedSourcesRaw
from visier_consolidated_analytics_python_sdk.paths.v1alpha_admin_consolidated_analytics_tenants_tenant_id_source_tenants.get import ListSourceTenantsRaw
from visier_consolidated_analytics_python_sdk.paths.v1alpha_admin_consolidated_analytics_tenants.get import ListTenantsRaw
from visier_consolidated_analytics_python_sdk.paths.v1alpha_admin_consolidated_analytics_tenants_tenant_id_excluded_sources.delete import RemoveExcludedSourcesRaw
from visier_consolidated_analytics_python_sdk.paths.v1alpha_admin_consolidated_analytics_tenants_tenant_id_source_tenants.delete import RemoveSourceTenantsRaw
from visier_consolidated_analytics_python_sdk.paths.v1alpha_admin_consolidated_analytics_tenants_tenant_id_excluded_sources.put import SetExcludedSourcesRaw
from visier_consolidated_analytics_python_sdk.paths.v1alpha_admin_consolidated_analytics_tenants_tenant_id_source_tenants.put import SetSourceTenantsRaw


class ConsolidatedAnalyticsV1AlphaApiRaw(
    AddExcludedSourcesRaw,
    AddSourceTenantsRaw,
    CreateTenantRaw,
    ListExcludedSourcesRaw,
    ListSourceTenantsRaw,
    ListTenantsRaw,
    RemoveExcludedSourcesRaw,
    RemoveSourceTenantsRaw,
    SetExcludedSourcesRaw,
    SetSourceTenantsRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
