# coding: utf-8

# flake8: noqa

"""
    Visier Consolidated Analytics APIs

    Visier APIs for managing consolidated analytics (CA) tenants.

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

__version__ = "22222222.99201.1200"

# import ApiClient
from visier_consolidated_analytics_python_sdk.api_client import ApiClient

# import Configuration
from visier_consolidated_analytics_python_sdk.configuration import Configuration

# import exceptions
from visier_consolidated_analytics_python_sdk.exceptions import OpenApiException
from visier_consolidated_analytics_python_sdk.exceptions import ApiAttributeError
from visier_consolidated_analytics_python_sdk.exceptions import ApiTypeError
from visier_consolidated_analytics_python_sdk.exceptions import ApiValueError
from visier_consolidated_analytics_python_sdk.exceptions import ApiKeyError
from visier_consolidated_analytics_python_sdk.exceptions import ApiException

from visier_consolidated_analytics_python_sdk.client import VisierConsolidatedAnalytics
