# coding: utf-8
"""
    Visier Consolidated Analytics APIs

    Visier APIs for managing consolidated analytics (CA) tenants.

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

import typing
import inspect
from datetime import date, datetime
from visier_consolidated_analytics_python_sdk.client_custom import ClientCustom
from visier_consolidated_analytics_python_sdk.configuration import Configuration
from visier_consolidated_analytics_python_sdk.api_client import ApiClient
from visier_consolidated_analytics_python_sdk.type_util import copy_signature
from visier_consolidated_analytics_python_sdk.apis.tags.consolidated_analytics_v1_alpha_api import ConsolidatedAnalyticsV1AlphaApi



class VisierConsolidatedAnalytics(ClientCustom):

    def __init__(self, configuration: typing.Union[Configuration, None] = None, **kwargs):
        super().__init__(configuration, **kwargs)
        if (len(kwargs) > 0):
            configuration = Configuration(**kwargs)
        if (configuration is None):
            raise Exception("configuration is required")
        api_client = ApiClient(configuration)
        self.consolidated_analytics_v1_alpha: ConsolidatedAnalyticsV1AlphaApi = ConsolidatedAnalyticsV1AlphaApi(api_client)
