# coding: utf-8

"""
    Visier Consolidated Analytics APIs

    Visier APIs for managing consolidated analytics (CA) tenants.

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

import unittest

import visier_consolidated_analytics_python_sdk
from visier_consolidated_analytics_python_sdk.model.consolidated_analytics_api_excluded_sources_list_dto_excluded_sources import ConsolidatedAnalyticsAPIExcludedSourcesListDTOExcludedSources
from visier_consolidated_analytics_python_sdk import configuration


class TestConsolidatedAnalyticsAPIExcludedSourcesListDTOExcludedSources(unittest.TestCase):
    """ConsolidatedAnalyticsAPIExcludedSourcesListDTOExcludedSources unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
